### ISSUE TITLE
TODO: Initial Release

### ISSUE THREAD

**Issue by angeloanan** [angeloanan/MPC-HC-DiscordRPC#1]
- [x] Detect if MPC-HC is running
- [x] Get the variables page
- [x] Parse the variables page
- [x] Update Discord Rich Presence
- [x] Set up Discord Rich Presence logo + details

**Comment by angeloanan** [comment]
Done. 
Thanks @liddack ! (#2 )
