### ISSUE TITLE
Add support for MPC-BE

### ISSUE THREAD

**Issue by liddack** [angeloanan/MPC-HC-DiscordRPC#3]
- [x] Create a new `indev` branch
- [ ] Merge [Der-Eddy/MPC-BE-DiscordRPC](https://github.com/Der-Eddy/MPC-BE-DiscordRPC/) to make the script work w/ both MPC-HC and MPC-BE
- [x] Add MPC-BE logo to Discord RP developer app
- [ ] Identify which MPC fork is running
- [ ] Display MPC-BE icon if MPC-BE is being used, and vice-versa
- [ ] Change README.md and package.json
- [ ] (if possible) Change the project name
- [ ] Merge changes to the master branch

**Comment by liddack** [comment]
Hey @angeloanan, what's up. I recently saw [Der-Eddy's fork of our project](https://github.com/Der-Eddy/MPC-BE-DiscordRPC/) and thougth it would be really nice if we add support for [MPC-BE](https://sourceforge.net/projects/mpcbe/). However it may require some changes in our project to make it allude it's not only for MPC-HC (as I mentioned [here](https://github.com/Der-Eddy/MPC-BE-DiscordRPC/commit/727cd8ecb90922d1ae1c8997931eb5aa8913c3a0#commitcomment-28990890)), including the project name.
What do you think?

**Comment by angeloanan** [comment]
Go ahead and add support for it! I can't help though since I somehow can't install MPC-BE. Good luck!

**Comment by liddack** [comment]
Thanks @angeloanan.  `MPC-DiscordRPC` sounds good to me

**Comment by liddack** [comment]
Actually, there's a way.

![Postman MPC-BE variables.html](https://i.imgur.com/rm0mMSH.png)
![MPC-BE server header](https://i.imgur.com/TwyKHtr.png)

We could easily get this info using `snekfetch`.
